name: 'Deployment Pipeline for Sandbox'
on:
  push:
    branches:
      - SS-395
  workflow_dispatch:
    inputs:
      dev:
        description: 'Deploy dev environment'
        required: true

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        run: echo "${{ github.event.inputs.sandbox}}"

      - name: Print some text
        run: echo "$MESSAGE" # prints the environmental variable, MESSAGE