name: 'Deployment Pipeline for Schedule'
on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    name: 'Deploy Pull Request'
    runs-on: ubuntu-latest
    steps:
      # print branch name eggarly ##
      - name: Get branch name
        run: echo 'The branch name is' ${GITHUB_REF##*/}
        
      - name: Retrieve version
        run: |
          echo "::set-output name=TAG_NAME::${{ github.event.pull_request.head.sha }}"

      - name: Retrieve version
        run: |
          echo "$tag_name"

      - name: greet
        id: greet
        run: |
          echo "environment is ${GITHUB_REF##*/}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          # echo "choice is on ${{ github.event.inputs.choice }}"
          # echo ::set-output name=exit_code::$?

      - uses: fregante/setup-git-user@v1
      # - run: git config user.name "$(git log -n 1 --pretty=format:%an)"
      # - run: git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: initial labeling after success
        if: ${{ success() && steps.greet.outcome == 'success' }}
        ### if: ${{ github.event.label.name == 'deploy' || github.event.pull_request.conclusion == 'success' }}
        uses: andymckay/labeler@master
        with:
          add-labels: "deployed-successfully"
          remove-labels: "deploy"

