name: 'Deployment Pipeline for Sandbox'
on:
 workflow_dispatch:
 push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: date
          echo "environment is ${GITHUB_REF##*/}
          # echo "boolean is ${{ github.event.inputs.boolean }}"
          # echo "choice is ${{ github.event.inputs.choice }}"
