name: 'Deployment Pipeline for Sandbox'
on:
  # schedule:
  #   - cron: 5 * * * *
  workflow_dispatch:
    inputs:
      sandbox 

jobs:
  Deployment:
    name: 'Deployment Pipeline For Testing'
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/checkout (Community)
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4