name: 'Deployment Pipeline for Sandbox'
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        options:
          - foo
          - bar
          - baz

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        run: echo "${{ github.event.inputs.sandbox}}"

      - name: Print some text
        run: echo "$MESSAGE" # prints the environmental variable, MESSAGE