# .github/workflows/deploy-bi.yml
name: Deploy BI

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Which BI application to deploy'
        required: true
        type: choice
        options:
          - tableau
          - powerbi
      environment:
        description: 'Target environment (select repository Environment)'
        required: true
        type: environment
      run_refresh:
        description: 'Run post-deploy data refresh'
        required: false
        type: boolean
        default: true

jobs:
  deploy_tableau:
    if: ${{ inputs.app == 'tableau' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Tableau assets
        run: echo "Deploying Tableau to ${{ inputs.environment }}..."
      - name: Refresh Tableau data
        if: ${{ inputs.run_refresh }}
        run: echo "Refreshing Tableau data..."

  deploy_powerbi:
    if: ${{ inputs.app == 'powerbi' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Power BI assets
        run: echo "Deploying Power BI to ${{ inputs.environment }}..."
      - name: Refresh Power BI data
        if: ${{ inputs.run_refresh }}
        run: echo "Refreshing Power BI data..."
