name: 'Deployment Pipeline for Schedule'
on:
  pull_request:
    types: [opened,synchronize,labeled,closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "environment is ${GITHUB_REF##*/}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is on ${{ github.event.inputs.choice }}"