name: 'Deployment Pipeline for Sandbox'
on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: 'Deploy the sandbox environment'
        required: false
        default: 'sandbox'
  schedule:
    - cron: '* * * * *'

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        run: echo "MESSAGE=${{ github.event.inputs.sandbox}}" >> $GITHUB_ENV

      - name: Print some text
        run: echo "$MESSAGE" # prints the environmental variable, MESSAGE