name: 'Deployment Pipeline for Schedule'
on:
  pull_request:
    types: [opened,labeled,closed]

jobs:
  build:
    if: ${{ github.event.action == 'opened' || ( github.event.action == 'labeled' && github.event.label.name == 'deploy' ) }}
    name: 'Deploy Pull Request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "environment is ${GITHUB_REF##*/}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is on ${{ github.event.inputs.choice }}"

      - name: initial labeling
        if: ${{ github.event.label.name == 'deploy' || github.event.pull_request.conclusion == 'success' }}
        uses: andymckay/labeler@master
        with:
          add-labels: "deployed-successfully"
          remove-labels: "deploy"

  Cleanup:
    name: 'Cleanup Pull Request'
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "environment is ${GITHUB_REF##*/}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          # echo "choice is on ${{ github.event.inputs.choice }}"