name: 'Deployment Pipeline for Sandbox'
on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: 'Deploy the sandbox environment'
        required: true

jobs:
  Deployment:
    name: 'Deployment Pipeline For Testing'
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/checkout (Community)
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4