name: 'Deployment Pipeline for Sandbox'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy sandbox environment'
        required: true
        default: 'sandbox'
#   schedule:
#     - cron: '* * * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
          # echo "boolean is ${{ github.event.inputs.boolean }}"
          # echo "choice is ${{ github.event.inputs.choice }}"
