name: 'Deployment Pipeline for Schedule'
on:
 workflow_dispatch:
 push:
 schedule:
   - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "environment is ${GITHUB_REF##*/}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          # echo "choice is ${{ github.event.inputs.choice }}"
