name: Manual Deployment to Master
on:
  # workflow_dispatch:
  #   inputs:
  #     target-branch:
  #       description: 'Target branch for deployment'
  #       required: true
  #       default: 'master'
  workflow_run:
    # branches: [feature/reusable-stage]
    workflows: [Remove labels]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check if the trigger branch is 'master'
      id: check_branch
      run: echo "Trigger branch is ${{ github.event.inputs.target-branch }}"
      
    - name: Deploy to Production (if on 'master')
      if: steps.check_branch.outputs.target-branch == 'master'
      run: |
        # Add your deployment commands here
        # For example, you can deploy to your production server
        # or trigger a deployment pipeline.
        echo "Deploying to production......."

  # staging:
  #   runs-on: ubuntu-latest
  #   if: steps.check_branch.outputs.target-branch == 'main'
  #   steps:
  #   - name: Check if the trigger branch is 'master'
  #     id: check_branch
  #     run: echo "Trigger branch is ${{ github.event.inputs.target-branch }}"
      
  #   - name: Deploy to Production (if on 'master')
  #     if: steps.check_branch.outputs.target-branch == 'master'
  #     run: |
  #       # Add your deployment commands here
  #       # For example, you can deploy to your production server
  #       # or trigger a deployment pipeline.
  #       echo "Deploying to production..."
