name: Manual Deployment to Master

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target branch for deployment'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
    steps:
    - name: Check if the trigger branch is 'master'
      id: check_branch
      run: echo "Trigger branch is ${{ github.event.inputs.target-branch }}"
      
    - name: Deploy to Production (if on 'master')
      if: steps.check_branch.outputs.target-branch == 'master'
      run: |
        # Add your deployment commands here
        # For example, you can deploy to your production server
        # or trigger a deployment pipeline.
        echo "Deploying to production..."

  second:
    if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Check if the trigger branch is 'master'
      id: check_branch
      run: echo "Trigger branch is ${{ github.event.inputs.target-branch }}"
      
    - name: Deploy to Production (if on 'master')
      if: steps.check_branch.outputs.target-branch == 'master'
      run: |
        # Add your deployment commands here
        # For example, you can deploy to your production server
        # or trigger a deployment pipeline.
        echo "Deploying to production..."