name: 'Deployment Pipeline for Sandbox'
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select Environment name
        options:
        - 
        - alex
        - bogdan
        - dev
        - joakim
        - mxkh
        - maxsolomatin
        - nataliia
        - stepan
        - sviat
        - tobias
        - viktor
      choice:
        type: choice
        description: Make a choice
        options:
        - print_text
        - bar
        - baz

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        run: echo "${{ github.event.inputs.sandbox}}"

      - name: Print some text
        run: echo "$MESSAGE" # prints the environmental variable, MESSAGE