name: Remove labels
on:
  workflow_run:
    workflows:
      - Deployment Pipeline for Schedule
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Labeler
      if: success()
      uses: crazy-max/ghaction-github-labeler@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        yaml-file: .github/labels.yml
        skip-delete: false
        dry-run: false
        exclude: |
          help*
          *issue

    - name: add labels
      uses: actions-ecosystem/action-add-labels@v1
      if: env.BASE_BRANCH != 'main'
      with:
        number: ${{ github.event.pull_request.number }}
        github_token: ${{ github.token }}
        labels: deployed-successfully


  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: remove labels
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          remove-labels: "deploy"
          repo-token: ${{ secrets.TOKEN }}

      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "deployment-failed"
          repo-token: ${{ secrets.TOKEN }}


