name: 'Perform Merge'
on:
  workflow_dispatch:

jobs:
  Rebase:
    name: 'Auto-rebase develop branch on push into main'
    runs-on: ubuntu-20.04
    steps:

      - name: Check out in Api Platform repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.TOKEN }}

      - name: Setup git user email and name
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
        continue-on-error: false

      - name: Checkout to main
        run: |
          git checkout main
        continue-on-error: false

      - name: Pull latest changes from main
        run: |
          git pull origin main
          git log --graph --pretty=format:%s
        continue-on-error: false

      - name: Checkout to develop
        run: |
          git checkout develop
        continue-on-error: false

      - name: Make sure develop has latest changes
        run: |
          git pull origin develop
        continue-on-error: false

      - name: Perform rebase
        run: |
          git rebase main
        continue-on-error: false

      - name: Force push changes to develop
        run: |
          git push origin develop -f
          git log --graph --pretty=format:%s
        continue-on-error: false
