name: PR Checker and Slack Notifier

on:
    push:
#   schedule:
#     # Define the schedule when you want to run this workflow (e.g., every day at 9 AM).
#     - cron: "0 9 * * *"

jobs:
  pr_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > github-cli.list.tmp
            sudo mv github-cli.list.tmp /etc/apt/sources.list.d/github-cli.list
            sudo apt update
            sudo apt install -y gh

      - name: Authenticate with GitHub
        run: gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: List PRs
        id: list-prs
        run: |
          ORGANIZATIONS=("clouddrove" "clouddrove-sandbox") # Add your GitHub organizations here
          PR_LIST=""
          for ORG in "${ORGANIZATIONS[@]}"; do
            PR_LIST+="\nPRs from $ORG:\n"
            PR_LIST+=$(gh pr list -R "$ORG" --json number,title,url --state all --limit 10 | jq -r '.[] | "• [\(.number)] \(.title) (\(.url))"')
          done
          echo "$PR_LIST" > pr_list.txt

      - name: Send PR links to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          PR_LIST=$(cat pr_list.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"$PR_LIST\"
          }" "$SLACK_WEBHOOK_URL"
