name: PR Checker and Slack Notifier

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - pre-release
          - dev
          - prod

      db_operation:
         description: 'Database operation to perform'
         required: false
         type: choice
         options:
           - backup
           - test
           - restore
           - restore-db

      run_db_dump:
        description: "Run DB dump?"
        required: true
        type: boolean
        default: false
      run_certbot:
        description: "Run Certbot?"
        required: true
        type: boolean
        default: false

jobs:
  pr_checker:
    runs-on: ubuntu-latest

    steps:
    - name: Check Pull Requests
      id: check_prs
      run: |
        ORGANIZATION="clouddrove"
        GITHUB_TOKEN="${{ secrets.TOKEN }}"
        
        PR_LIST=$(gh api "/orgs/$ORGANIZATION/repos" -q ".[].pulls_url" | xargs -I % gh api % -q ".[].html_url")

        echo "::set-output name=pr_list::$PR_LIST"

    - name: Send PR URLs to Slack
      id: send_to_slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        PR_LIST="${{ steps.check_prs.outputs.pr_list }}"
        SLACK_MESSAGE="Here are the latest Pull Requests in the organization:\n\n$PR_LIST"
        
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$SLACK_MESSAGE\"}" $SLACK_WEBHOOK_URL
