name: 'Rebase environment'
on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: 'Deploy Pull Request'
    # if: ${{github.event.action == 'labeled' && github.event.label.name == 'rebase' || github.ref == 'refs/heads/SS-434'}}
    runs-on: ubuntu-20.04
    steps:

      - name: Check out in platform-api repo
        uses: actions/checkout@v2.3.4
        # with: 
        #   ref: develop
        #   token: ${{ secrets.TOKEN }}

      - name: perform merge
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin main
          git fetch origin develop
          git checkout -b origin/develop origin/develop
          git rebase origin/main
          git push --force-with-lease origin origin/develop:develop
          # git add . && git commit -m "Merge with main"
          git push -f origin develop
        continue-on-error: true

      # - name: 'Rebase from main'
      #   run: |
      #     git config --global user.email "${GITHUB_ACTOR}"
      #     git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
      #     git rebase origin/HEAD

  # main:
  #   if: ${{ github.event.label.name == 'merge' }}
  #   name: Merge Main
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: git checkout
  #       uses: actions/checkout@v2
  #       with:
  #         token: ${{ secrets.TOKEN }}
  #         ref: ${{ github.event.pull_request.head.ref }}
  #         fetch-depth: 0

  #     - name: perform merge
  #       run: |
  #         git config --global user.email "${GITHUB_ACTOR}"
  #         git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
  #         git status
  #         git pull
  #         git checkout "$DEFAULT_BRANCH"
  #         git status
  #         git checkout "$GITHUB_HEAD_REF"
  #         git merge "$DEFAULT_BRANCH" --no-edit
  #         git push
  #         git status

  #     - name: remove label
  #       if: always()
  #       uses: actions-ecosystem/action-remove-labels@v1
  #       with:
  #         labels: merge main